showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
mixinText: >-
  mixin: # object
    dns:
      enable: true
      ipv6: false
      listen: 0.0.0.0:53
      enhanced-mode: redir-host
      fake-ip-range: 198.18.0.1/16
      use-hosts: true
      fake-ip-filter:   
        - '*.lan'
        - localhost.ptlogin2.qq.com
        - "dns.msftncsi.com"
        - "www.msftncsi.com"
        - "www.msftconnecttest.com" 
        - '+.srv.nintendo.net'
        - '+.stun.playstation.net'
        - '+.msftconnecttest.com'
        - '+.msftncsi.com'
        - '+.xboxlive.com'
        - 'msftconnecttest.com'
        - 'xbox.*.microsoft.com'
        - '*.battlenet.com.cn'
        - '*.battlenet.com'
        - '*.blzstatic.cn'
        - '*.battle.net'
      nameserver:
        - tls://doh.pub:853
        - tls://dns.alidns.com:853
        - https://dns.pub/dns-query
        - https://223.5.5.5/dns-query
        - 223.5.5.5 
        - 114.114.114.114
        - 119.29.29.29
        - 182.254.116.116
        - 202.101.172.35
        - 202.101.172.47
      fallback:
        - tls://dns.google:853
        - tls://1.1.1.1:853
        - https://1.1.1.1/dns-query
        - tcp://1.1.1.1
        - tls://dns.rubyfish.cn:853
        - 1.1.1.1
        - 8.8.8.8   
        - tls://8.8.4.4:853
        - tls://1.0.0.1:853
      fallback-filter:
        geoip: true
        ipcidr:
          - 240.0.0.0/4
    hosts:
      'bbs.vcb-s.com': 47.240.95.103
      'dmhy.org': 104.25.27.31
      '*.dmhy.org': 104.25.27.31
      'hdchina.org': 172.67.148.83
      '*.hdchina.org': 172.67.148.83
    tun:
      enable: true
      stack: gvisor
      dns-hijack:
        - 198.18.0.2:53
      macOS-auto-route: true
      macOS-auto-detect-interface: true

  #tun网卡无网络权限解决方法

  #打开注册表路径 HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Windows\NetworkConnectivityStatusIndicator

  #新建一个名为DisablePassivePolling的DWORD，值为0，重启
theme: 1
interfaceName: Clash
bypassText: |
  bypass:
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
