theme: 1
showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
mixinText: |-
  mixin: # object
    dns:
      enable: true
      ipv6: false
      enhanced-mode: redir-host
      nameserver:
        - https://dns.pub/dns-query
        - https://223.5.5.5/dns-query
        - 114.114.114.114
        - 119.29.29.29
        - 182.254.116.116
        - 202.101.172.35
        - 202.101.172.47
      fallback:
        - https://1.1.1.1/dns-query
        - tcp://1.1.1.1
        - tls://dns.rubyfish.cn:853
        - tls://8.8.4.4:853
        - tls://1.0.0.1:853
    hosts:
        'bbs.vcb-s.com': 47.240.95.103
        'dmhy.org': 104.25.27.31
        '*.dmhy.org': 104.25.27.31
        'hdchina.org': 172.67.148.83
        '*.hdchina.org': 172.67.148.83
    tun:
      enable: true
      stack: gvisor
      dns-hijack:
        - 198.18.0.2:53
      macOS-auto-route: true
      macOS-auto-detect-interface: true
interfaceName: ""
profileParsersText: |
  parsers: # array
systemProxyTypeIndex: 0
bypassText: |
  bypass:
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
pacContentText: >-
  function FindProxyForURL(url, host) {
    return "PROXY 127.0.0.1:%mixed-port%; SOCKS5 127.0.0.1:%mixed-port%; DIRECT;"
  }
shortcutSystemProxy: ""
childProcessText: |
  processes: # array
runTimeFormat: "hh : mm : ss"
editor: 0
iconSpeed: false
