ixinText: |-
  mixin: # object
    dns:
      enable: true
      ipv6: false
      enhanced-mode: redir-host
      nameserver:
        - 114.114.114.114
        - 119.29.29.29
        - 182.254.116.116
        - 202.101.172.35
        - 202.101.172.47
        - https://dns.pub/dns-query
        - https://223.5.5.5/dns-query
      fallback:
        - tcp://1.1.1.1
        - tls://dns.rubyfish.cn:853
        - tls://8.8.4.4:853
        - tls://1.0.0.1:853
        - https://1.1.1.1/dns-query
    tun:
      enable: true
      stack: gvisor
      dns-hijack:
        - 198.18.0.2:53
      auto-route: true
      auto-detect-interface: true
showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
shortcutMixin: ""
