port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.10.0.1/16
  nameserver:
    - 119.29.29.29
    - 114.114.114.114
    - 223.5.5.5
    - tls://dns.rubyfish.cn:853
    - https://dns.alidns.com/dns-query
    - https://rubyfish.cn/dns-query
  fallback:
    - tls://1.0.0.1:853
    - dns.google:853
    - dns.google/dns-query
    - tls://dns.rubyfish.cn:853  
hosts:
  services.googleapis.cn: 172.217.24.195
  young-cell-3dd2.dyphire.workers.dev: 104.17.144.237
proxies: ~
proxy-groups: ~
rules: ~
{% else %}
  enhanced-mode: redir-host
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.rixcloud.dev/dns-query
    - https://120.25.25.166/dns-query
proxies: ~
proxy-groups: ~
rules: ~
{% endif %}
