# tun模式基础设置，注意缩进!
mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
dns:
  enable: true                   # set true to enable dns (default is false)
  ipv6: false                    # default is false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host      # or fake-ip
  fake-ip-range: 198.18.0.1/16   # if you don't know what it is, don't change it
  use-hosts: true                # lookup hosts and return IP record
  fake-ip-filter:                # fake ip white domain list, aka Always Real IP
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - "dns.msftncsi.com"
    - "www.msftncsi.com"
    - "www.msftconnecttest.com"
  nameserver:
    - 223.5.5.5                  # 阿里DNS
    - 114.114.114.114            # 114DNS 
    - tls://doh.pub:853
    - tls://dns.alidns.com:853
    - https://dns.pub/dns-query
    - https://223.5.5.5/dns-query
    - 119.29.29.29
    - 182.254.116.116
    - 202.101.172.35
    - 202.101.172.47  
  fallback:                      # concurrent request with nameserver, 
    - 1.1.1.1                    # cloudflare
    - 8.8.8.8                    # google
    - tls://dns.google:853
    - tls://1.1.1.1:853
    - https://1.1.1.1/dns-query
    - tcp://1.1.1.1
    - tls://dns.rubyfish.cn:853  
    - tls://8.8.4.4:853
    - tls://1.0.0.1:853
  fallback-filter: 
    geoip: true                  # default    
    ipcidr:                      # ips in these subnets will be considered polluted
      - 240.0.0.0/4
hosts:
  'bbs.vcb-s.com': 47.240.95.103
  'dmhy.org': 104.25.27.31
  '*.dmhy.org': 104.25.27.31
  'hdchina.org': 172.67.148.83
  '*.hdchina.org': 172.67.148.83
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true
